/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/sourcenetwork/defradb/cbindings */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 13 "acp.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "add_collection.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "block.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "collection.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "document.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "encrypted_index.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "identity.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "index.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "lens.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "node.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "p2p.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "query.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "txn.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "version.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "view.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern Result ACPAddDACPolicy(uintptr_t nodePtr, uintptr_t identityPtr, char* policy);
extern Result ACPAddDACActorRelationship(uintptr_t nodePtr, uintptr_t identityPtr, char* collection, char* docID, char* relation, char* actor);
extern Result ACPDeleteDACActorRelationship(uintptr_t nodePtr, uintptr_t identityPtr, char* collection, char* docID, char* relation, char* actor);
extern Result ACPDisableNAC(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result ACPReEnableNAC(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result ACPAddNACActorRelationship(uintptr_t nodePtr, uintptr_t identityPtr, char* relation, char* actor);
extern Result ACPDeleteNACActorRelationship(uintptr_t nodePtr, uintptr_t identityPtr, char* relation, char* actor);
extern Result ACPGetNACStatus(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result AddCollection(uintptr_t nodePtr, char* sdl, uintptr_t identityPtr);
extern Result VerifyBlockSignature(uintptr_t nodePtr, char* keyType, char* publicKey, char* cid, uintptr_t identityPtr);
extern Result DescribeCollection(uintptr_t nodePtr, CollectionOptions opts, uintptr_t identityPtr);
extern Result PatchCollection(uintptr_t nodePtr, char* patch, char* lensConfig, uintptr_t identityPtr);
extern Result SetActiveCollection(uintptr_t nodePtr, CollectionOptions opts, uintptr_t identityPtr);
extern Result TruncateCollection(uintptr_t nodePtr, CollectionOptions opts, uintptr_t identityPtr);
extern Result AddDocument(uintptr_t nodePtr, char* json, int isEncrypted, char* encryptedFields, CollectionOptions opts, uintptr_t identityPtr);
extern Result DeleteDocument(uintptr_t nodePtr, char* docIDStr, char* filterStr, CollectionOptions opts, uintptr_t identityPtr);
extern Result GetDocument(uintptr_t nodePtr, char* docIDStr, int showDeleted, CollectionOptions opts, uintptr_t identityPtr);
extern Result UpdateDocument(uintptr_t nodePtr, char* docIDStr, char* filterStr, char* updaterStr, CollectionOptions opts, uintptr_t identityPtr);
extern Result NewEncryptedIndex(uintptr_t nodePtr, char* collectionName, char* fieldName, uintptr_t identityPtr);
extern Result ListEncryptedIndexes(uintptr_t nodePtr, char* collectionName, uintptr_t identityPtr);
extern Result DeleteEncryptedIndex(uintptr_t nodePtr, char* collectionName, char* fieldName, uintptr_t identityPtr);
extern NewIdentityResult NewIdentity(char* keyType);
extern Result GetNodeIdentity(uintptr_t nodePtr);
extern void FreeIdentity(uintptr_t identityPtr);
extern Result NewIndex(uintptr_t nodePtr, char* indexName, char* fieldsStr, int isUnique, CollectionOptions options, uintptr_t identityPtr);
extern Result ListIndexes(uintptr_t nodePtr, CollectionOptions options, uintptr_t identityPtr);
extern Result DeleteIndex(uintptr_t nodePtr, char* indexName, CollectionOptions options, uintptr_t identityPtr);
extern Result SetLens(uintptr_t nodePtr, uintptr_t identityPtr, char* src, char* dst, char* cfg);
extern Result AddLens(uintptr_t nodePtr, uintptr_t identityPtr, char* cfg);
extern Result ListLenses(uintptr_t nodePtr, uintptr_t identityPtr);
extern NewNodeResult NewNode(NodeInitOptions cOptions);
extern Result CloseNode(uintptr_t nodePtr);
extern Result GetP2PInfo(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result ListP2PActivePeers(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result ListP2PReplicators(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result AddP2PReplicator(uintptr_t nodePtr, char* collections, char* addresses, uintptr_t identityPtr);
extern Result DeleteP2PReplicator(uintptr_t nodePtr, char* collections, char* id, uintptr_t identityPtr);
extern Result AddP2PCollection(uintptr_t nodePtr, char* collections, uintptr_t identityPtr);
extern Result DeleteP2PCollection(uintptr_t nodePtr, char* collections, uintptr_t identityPtr);
extern Result ListP2PCollections(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result AddP2PDocument(uintptr_t nodePtr, char* collections, uintptr_t identityPtr);
extern Result DeleteP2PDocument(uintptr_t nodePtr, char* collections, uintptr_t identityPtr);
extern Result ListP2PDocuments(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result SyncP2PDocuments(uintptr_t nodePtr, char* collection, char* docIDs, char* timeoutStr, uintptr_t identityPtr);
extern Result SyncP2PCollectionVersions(uintptr_t nodePtr, char* versionIDs, char* timeoutStr, uintptr_t identityPtr);
extern Result SyncP2PBranchableCollection(uintptr_t nodePtr, char* collectionID, char* timeoutStr, uintptr_t identityPtr);
extern Result ConnectP2PPeers(uintptr_t nodePtr, char* peerAddresses, uintptr_t identityPtr);
extern Result PollSubscription(char* id);
extern Result CloseSubscription(char* id);
extern Result ExecuteQuery(uintptr_t nodePtr, char* query, uintptr_t identityPtr, char* operationName, char* variables);
extern NewTxnResult CreateTransaction(uintptr_t nodePtr, int isReadOnly);
extern Result CommitTransaction(uintptr_t txnPtr);
extern void DiscardTransaction(uintptr_t txnPtr);
extern Result GetVersion(int flagFull, int flagJSON);
extern Result AddView(uintptr_t nodePtr, char* query, char* sdl, char* transformCIDStr, uintptr_t identityPtr);
extern Result RefreshView(uintptr_t nodePtr, CollectionOptions cOptions, uintptr_t identityPtr);

#ifdef __cplusplus
}
#endif
