/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/sourcenetwork/defradb/cbindings */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 13 "acp.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "block.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "collection.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "identity.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "index.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "lens.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "node.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "p2p.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "query.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "schema.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "txn.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "version.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"

#line 13 "view.go"

#include <stdlib.h>
#include "defra_structs.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern Result ACPAddDACPolicy(uintptr_t nodePtr, uintptr_t identityPtr, char* policy);
extern Result ACPAddDACActorRelationship(uintptr_t nodePtr, uintptr_t identityPtr, char* collection, char* docID, char* relation, char* actor);
extern Result ACPDeleteDACActorRelationship(uintptr_t nodePtr, uintptr_t identityPtr, char* collection, char* docID, char* relation, char* actor);
extern Result ACPDisableNAC(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result ACPReEnableNAC(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result ACPAddNACActorRelationship(uintptr_t nodePtr, uintptr_t identityPtr, char* relation, char* actor);
extern Result ACPDeleteNACActorRelationship(uintptr_t nodePtr, uintptr_t identityPtr, char* relation, char* actor);
extern Result ACPGetNACStatus(uintptr_t nodePtr, uintptr_t identityPtr);
extern Result BlockVerifySignature(uintptr_t nodePtr, char* keyType, char* publicKey, char* cid);
extern Result CollectionCreate(uintptr_t nodePtr, char* json, int isEncrypted, char* encryptedFields, CollectionOptions options);
extern Result CollectionDelete(uintptr_t nodePtr, char* docIDStr, char* filterStr, CollectionOptions options);
extern Result CollectionDescribe(uintptr_t nodePtr, CollectionOptions options);
extern Result CollectionListDocIDs(uintptr_t nodePtr, CollectionOptions options);
extern Result CollectionGet(uintptr_t nodePtr, char* docIDStr, int showDeleted, CollectionOptions options);
extern Result CollectionPatch(uintptr_t nodePtr, char* patch, char* lensConfig, CollectionOptions options);
extern Result CollectionUpdate(uintptr_t nodePtr, char* docIDStr, char* filterStr, char* updaterStr, CollectionOptions options);
extern Result SetActiveCollection(uintptr_t nodePtr, char* version);
extern NewIdentityResult IdentityNew(char* keyType);
extern Result NodeIdentity(uintptr_t nodePtr);
extern Result IndexCreate(uintptr_t nodePtr, char* collectionName, char* indexName, char* fieldsStr, int isUnique);
extern Result IndexList(uintptr_t nodePtr, char* collectionName);
extern Result IndexDrop(uintptr_t nodePtr, char* collectionName, char* indexName);
extern Result LensSet(uintptr_t nodePtr, char* src, char* dst, char* cfg);
extern Result LensDown(uintptr_t nodePtr, char* collectionID, char* documents);
extern Result LensUp(uintptr_t nodePtr, char* collectionID, char* documents);
extern Result LensReload(uintptr_t nodePtr);
extern Result LensSetRegistry(uintptr_t nodePtr, char* collectionID, char* cfg);
extern NewNodeResult NewNode(NodeInitOptions cOptions);
extern Result NodeClose(uintptr_t nodePtr);
extern Result P2PInfo(uintptr_t nodePtr);
extern Result P2PgetAllReplicators(uintptr_t nodePtr);
extern Result P2PsetReplicator(uintptr_t nodePtr, char* collections, char* peerInfo);
extern Result P2PdeleteReplicator(uintptr_t nodePtr, char* collections, char* peerInfo);
extern Result P2PcollectionAdd(uintptr_t nodePtr, char* collections);
extern Result P2PcollectionRemove(uintptr_t nodePtr, char* collections);
extern Result P2PcollectionGetAll(uintptr_t nodePtr);
extern Result P2PdocumentAdd(uintptr_t nodePtr, char* collections);
extern Result P2PdocumentRemove(uintptr_t nodePtr, char* collections);
extern Result P2PdocumentGetAll(uintptr_t nodePtr);
extern Result P2PdocumentSync(uintptr_t nodePtr, char* collection, char* docIDs, char* timeoutStr);
extern Result P2Pconnect(uintptr_t nodePtr, char* peerID, char* peerAddresses);

// PollSubscription will get the subscription object associcated with an ID, and if
// it exists will see if there's a message in its result channel. If there isn't, it will
// return with status 2, and a blank payload. If there is, it will return with status 0,
// and the payload of the message. If an error occurs, status 1 is returned.
//
extern Result PollSubscription(char* id);
extern Result CloseSubscription(char* id);
extern Result ExecuteQuery(uintptr_t nodePtr, char* query, uintptr_t identityPtr, char* operationName, char* variables);
extern Result AddSchema(uintptr_t nodePtr, char* schema, uintptr_t identityPtr);
extern NewTxnResult TransactionCreate(uintptr_t nodePtr, int isConcurrent, int isReadOnly);
extern Result TransactionCommit(uintptr_t txnPtr);
extern void TransactionDiscard(uintptr_t txnPtr);
extern Result VersionGet(int flagFull, int flagJSON);
extern Result ViewAdd(uintptr_t nodePtr, char* query, char* sdl, char* transformStr);
extern Result ViewRefresh(uintptr_t nodePtr, char* viewNameStr, char* collectionIDStr, char* versionIDStr, int getInactive);

#ifdef __cplusplus
}
#endif
